//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace veri
{
    using System;
    using System.Collections.Generic;
    
    public partial class FooterLinkler
    {
        public int Fid { get; set; }
        public int kullanicid { get; set; }
        public string FLinkAdi { get; set; }
        public string FLinkUrl { get; set; }
        public string Ftarih { get; set; }
        public string FAktifMi { get; set; }
    
        public virtual Kullanicilar Kullanicilar { get; set; }
    }
}
