//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace veri
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hizmetler
    {
        public int Hizmetlerid { get; set; }
        public int kullanicid { get; set; }
        public string HizmetlerAdi { get; set; }
        public string HizmetlerUrl { get; set; }
        public string HizmetlerYazi { get; set; }
        public string HizmetlerTarih { get; set; }
        public string HizmetlerAktif { get; set; }
        public string HizmetlerResim { get; set; }
        public string HizmetlerAnahtar { get; set; }
        public string HizmetKisaYazi { get; set; }
        public string HizmetlerClass { get; set; }
    
        public virtual Kullanicilar Kullanicilar { get; set; }
    }
}
