//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace veri
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kategoriler
    {
        public int Kategorid { get; set; }
        public string kategoriAdi { get; set; }
        public string KategoriYazi { get; set; }
        public string KategoriResim { get; set; }
        public string KategoriAktif { get; set; }
        public int kullanicid { get; set; }
        public int Menulerid { get; set; }
        public string KategorilerUrl { get; set; }
        public string kategorilertarih { get; set; }
    
        public virtual Menuler Menuler { get; set; }
        public virtual Kullanicilar Kullanicilar { get; set; }
    }
}
