//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace veri
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        public int Menuid { get; set; }
        public int Menulerid { get; set; }
        public string Resim { get; set; }
        public string Yazi { get; set; }
        public string Menuaktif { get; set; }
        public int kullanicid { get; set; }
        public string Menutarih { get; set; }
    
        public virtual Menuler Menuler { get; set; }
        public virtual Kullanicilar Kullanicilar { get; set; }
    }
}
