//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace veri
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menuler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Menuler()
        {
            this.Kategorilers = new HashSet<Kategoriler>();
            this.Menus = new HashSet<Menu>();
        }
    
        public int Menulerid { get; set; }
        public string MenuAdi { get; set; }
        public string MenuUrl { get; set; }
        public string MenuTarih { get; set; }
        public string MenuAktif { get; set; }
        public string KategoriMi { get; set; }
        public string MenuMi { get; set; }
        public int kullanicid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kategoriler> Kategorilers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Menu> Menus { get; set; }
        public virtual Kullanicilar Kullanicilar { get; set; }
    }
}
