//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace veri
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiteAyar
    {
        public int SiteAyarid { get; set; }
        public int kullanicid { get; set; }
        public string SiteAdi { get; set; }
        public string SiteLogo { get; set; }
        public string SiteMail { get; set; }
        public string SiteSmtp { get; set; }
        public string SiteMailSifre { get; set; }
        public string SiteTelefon { get; set; }
        public string SiteAdres { get; set; }
        public string SiteİnfoMail { get; set; }
    
        public virtual Kullanicilar Kullanicilar { get; set; }
    }
}
