//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace veri
{
    using System;
    using System.Collections.Generic;
    
    public partial class Slider
    {
        public int Sliderid { get; set; }
        public int kullanicid { get; set; }
        public System.DateTime SliderTarih { get; set; }
        public string SliderAdi { get; set; }
        public string AkitfMi { get; set; }
        public string SliderResimAdi { get; set; }
    
        public virtual Kullanicilar Kullanicilar { get; set; }
    }
}
